branches:
  - main
  - name: dev
    prerelease: true

tagFormat: "v${version}"

plugins:
  - "@semantic-release/commit-analyzer"

  - "@semantic-release/release-notes-generator"

  - ["@semantic-release/changelog", { "changelogFile": "CHANGELOG.md" }]

  # Update project version
  - [
      "@semantic-release/exec",
      { "prepareCmd": 'printf "${nextRelease.version}" > VERSION' },
    ]

  # Commit generated files
  - [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.md", "VERSION"],
        "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}",
      },
    ]

  # Create GitHub tag and publish release
  - [
      "@semantic-release/github",
      {
        "assets":
          [
            { "path": "VERSION", "label": "Version File" },
            { "path": "CHANGELOG.md", "label": "Changelog" },
          ],
      },
    ]

preset: conventionalcommits

releaseRules:
  # Normal rules
  # - type: fix
  #   release: patch
  # - type: feat
  #   release: minor

  # BREAKING CHANGES during v0.x → minor, not major
  # - breaking: true
  #   release: minor

  - type: docs
    release: false
  - type: ci
    release: false
  - type: chore
    release: false
